# Étape 1 : Utiliser une image de base stable
FROM node:18

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package.json package-lock.json /app/

# Étape 4 : Installer les dépendances
RUN npm install --omit=dev

# Étape 5 : Copier le reste des fichiers
COPY . /app/

# Étape 6 : Construire l'application
RUN npm run build

# Étape 7 : Commande par défaut pour démarrer l'application
CMD ["npm", "start"]
